"""Initial db schema

Revision ID: e199fad30ead
Revises: 
Create Date: 2022-09-19 23:12:10.973258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e199fad30ead'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('received', sa.DateTime(), nullable=False),
    sa.Column('department', sa.String(length=20), nullable=False),
    sa.Column('form_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_for_support',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('remote_addr', sa.String(length=70), nullable=False),
    sa.Column('description_of_the_problem', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('urgent', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_for_support')
    op.drop_table('event')
    # ### end Alembic commands ###
