version: '3.8'
 
services:
 
  rabbitmq:
    build: ./rabbitmq
    environment:
        # The RABBITMQ_DEFAULT_USER is used
        # to connect to the web admin
        RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
        RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
        RABBITMQ_LOGS: "WARNING"
    networks:
      - external
      - internal
    ports:
        - "15672:15672" # Web admin port
        - "5672:5672"   # Do not expose this port in production

  mysql:
    image: mariadb:latest
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - internal

  drupal:
    image: drupal:9.4.5
    ports:
      - 8080:80
    container_name: drupal
    depends_on:
      - mysql
      - ingestor
    restart: unless-stopped
    networks:
      - internal
      - external
    volumes:
      - drupal-data:/var/www/html

  ingestor:
    build:
      context: python
      dockerfile: ingestor/Dockerfile-local
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: "${RABBITMQ_HOST}"
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASS: "${RABBITMQ_PASS}"
    networks:
      - external
    ports:
      - 5000:5000


  form_handler:
    build:
      context: python
      dockerfile: form_handler/Dockerfile-local
    depends_on:
      - rabbitmq
      - ingestor
    environment:
      RABBITMQ_HOST: "${RABBITMQ_HOST}"
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASS: "${RABBITMQ_PASS}"
      X_STREAM_OFFSET: "first"
    networks:
      - internal


networks:
  external:
    driver: bridge
  internal:
    driver: bridge

volumes:
  drupal-data:
  db-data:
